coffee/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('coffee_app.urls','coffee_app'),namespace='coffee_app')),
    path('users/', include(( 'users.urls','users'), namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

coffee_app/urls.py
from django.contrib import admin
from django.urls import path
from . import views
urlpatterns = [
    path('', views.index, name='index'),
    path('items/', views.items, name='items'),
    path('getnews/',views.get_news, name="news"),
    path('getpromotions/',views.get_promotion, name="promotion"),
    path('', views.items, name='index'),
    path('admin/',admin.site.urls),
    path('news/',views.news, name = "news"),
    path('newsdetail/<int:id>/',views.news_detail, name = "newsdetail"),
    path('orderhistory/',views.orderhistory, name = "orderhistory"),
    path('items/favourite/', views.items_detail_1, name="type1"),
    path('items/coffee/', views.items_detail_2, name="type2"),
    path('items/tea/', views.items_detail_3, name="type3"),
    path('items/ice/', views.items_detail_4, name="type4"),
    path('items/snack/', views.items_detail_5, name="type5"),
    path('order/', views.order, name='order'),
    path('update_item/', views.updateItem, name='update_item'),
    path('remove_item/', views.removeItem, name='remove_item'),
    path('update_promotion/', views.update_promotion, name='update_promotion'),
    path('process_order/', views.processOrder, name='process_order'),
    path('store/', views.store, name='store'),

]

users/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import path
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import LoginView,LogoutView

from . import views

app_name='users'
urlpatterns = [
    path('login/', LoginView.as_view(template_name='users/login.html'),name='login'),
    path('logout/', views.logout_view,name='logout'),
    path('register/', views.register,name='register'),
    ##test
    
    #path('detailaccount/<int:pk>/',views.account_detail),
    path('account/', views.accountAPIview.as_view()),
    path('account/<int:id>',views.account_detail.as_view()),
    path('account/customer/', views.customerAPIview.as_view()),
    path('account/customer/<int:id_account>', views.customer_detail.as_view()),
]

users/models.py
from __future__ import unicode_literals
from django.db import models

# Create your models here.
from django.contrib import admin

from django.db.models.fields.related import ForeignKey

class account(models.Model):
    username = models.CharField(null=False,help_text="Enter your phone number",max_length=15)
    password = models.CharField(max_length=30)
    id =models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')
    def get_absolute_url(self):
        """
        Returns the url to access a particular instance of Product.
        """
        return reverse('account-detail-view', args=[str(self.id)])

    def __str__(self):
        return self.id


class customer(models.Model):
    name = models.CharField(max_length=100)
    phone = models.CharField(default=0,primary_key=True,max_length=15)
    dateofbirth = models.DateField(null=False)
    Address = models.CharField(max_length=50)
    id_account = models.ForeignKey(account,on_delete=models.CASCADE)

    def __str__(self):
        return self.name

class Credit_card(models.Model):
    id_card = models.PositiveBigIntegerField(default=0, primary_key=True)
    id_user = models.ForeignKey(account,on_delete=models.CASCADE)
    bank = models.CharField(max_length=15)
    expired_day = models.DateTimeField()
    account_name = models.CharField(max_length=100)

    def __str__(self):
        return self.id_card

users/views.py
import abc
from django.shortcuts import render
from django.contrib.auth import logout,login,authenticate
from django.contrib.auth.forms import UserCreationForm

from coffee_app.models import Customer



from django.urls import reverse
from django.http import HttpResponseRedirect
# Create your views here.
def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('coffee_app:index'))

def register(request):
    if request.method != 'POST':
        # Display blank registration form.
        form = UserCreationForm()
    else:
        # Process completed form.
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            Customer.objects.create(
            user= new_user,
            name= new_user.username,
            email= new_user.username + "@gmail.com",
            )
            # Log the user in and then redirect to home page.
            authenticated_user = authenticate(username=new_user.username,
                password=request.POST['password1'])
            login(request, authenticated_user)
            return HttpResponseRedirect(reverse('coffee_app:index'))
    context = {'form': form}
    return render(request, 'users/register.html', context)
    

users/templates/users/login.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href=" {% static './components/login/style.css' %} ">
    <script src="http://code.jquery.com/jquery-1.11.0.min.js"></script>

    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

    <title>Document</title>
</head>
<body>
    <div class="login-reg-panel">
		
							
		<div class="register-info-box">
			<h2>Don't have an account?</h2>
			<p>Creare an account</p>
			<label id="label-login" for="log-login-show">
			 <a href="{% url 'users:register' %}" style="color: white" >register</a> </label>


			<input type="radio" name="active-log-panel" id="log-login-show">
		</div>
							
		<div class="white-panel">
			<div class="login-show">
                
				<h2>LOGIN</h2>
				
                <!-- fix	 -->
                <form method="post" action="{% url 'users:login' %}">
                {%csrf_token%}
                {{ form.as_p }}
                    <!-- <button name="submit" value="Login">login</button> -->
                    <input type="submit" type="button" value="Login" style="background-color: #fb8d17" >
				    <input type="hidden" name="next" value="{% url 'coffee_app:index' %}" />
                </form>
                <!-- fix -->

                
                <a href=" {% static '' %} ">Forgot password?</a>
			</div>
			
		</div>
	</div>
    <script src=" {% static './components/login/script.js' %} "></script>

</body>
</html>

users/templates/users/register.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href=" {% static './components/login/style.css' %} ">
    <script src="http://code.jquery.com/jquery-1.11.0.min.js"></script>

    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

    <title>Document</title>
</head>
<body>
    <div class="login-reg-panel">
						
		<div class="register-info-box">
			<h2>Have an account?</h2>
			
			<label id="label-register" for="log-reg-show">
                 <a href="{% url 'users:login' %}" style="color:white">login now</a>

                
        </label>

		</div>		
		<div class="white-panel-reg">
			<div class="login-show">
                
				<h2>RESGISTATION FORM</h2>
				
                <!-- fix	 -->
                <form method="post" action="{% url 'users:register' %}"> 
                    {% csrf_token %}
                    {{ form.as_p }}
                    <!-- <button name="submit">register</button> -->
                    <input type="submit" type="button" value="Register" style="background-color: #fb8d17">
                    <input type="hidden" name="next" value="{% url 'coffee_app:index' %}" /> </form>
                <!-- fix -->
    			</div>
			
		</div>
	</div>
    <script src=" {% static './components/login/script.js' %} "></script>

</body>
</html>