coffee/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('coffee_app.urls','coffee_app'),namespace='coffee_app')),
    path('users/', include(( 'users.urls','users'), namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

coffee_app/urls.py
from django.contrib import admin
from django.urls import path
from . import views
urlpatterns = [
    path('', views.index, name='index'),
    path('items/', views.items, name='items'),
    path('getnews/',views.get_news, name="news"),
    path('getpromotions/',views.get_promotion, name="promotion"),
    path('', views.items, name='index'),
    path('admin/',admin.site.urls),
    path('news/',views.news, name = "news"),
    path('newsdetail/<int:id>/',views.news_detail, name = "newsdetail"),
    path('orderhistory/',views.orderhistory, name = "orderhistory"),
    path('items/favourite/', views.items_detail_1, name="type1"),
    path('items/coffee/', views.items_detail_2, name="type2"),
    path('items/tea/', views.items_detail_3, name="type3"),
    path('items/ice/', views.items_detail_4, name="type4"),
    path('items/snack/', views.items_detail_5, name="type5"),
    path('order/', views.order, name='order'),
    path('update_item/', views.updateItem, name='update_item'),
    path('remove_item/', views.removeItem, name='remove_item'),
    path('update_promotion/', views.update_promotion, name='update_promotion'),
    path('process_order/', views.processOrder, name='process_order'),
    path('store/', views.store, name='store'),

]

users/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import path
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import LoginView,LogoutView

from . import views

app_name='users'
urlpatterns = [
    path('login/', LoginView.as_view(template_name='users/login.html'),name='login'),
    path('logout/', views.logout_view,name='logout'),
    path('register/', views.register,name='register'),
    ##test
    
    #path('detailaccount/<int:pk>/',views.account_detail),
    path('account/', views.accountAPIview.as_view()),
    path('account/<int:id>',views.account_detail.as_view()),
    path('account/customer/', views.customerAPIview.as_view()),
    path('account/customer/<int:id_account>', views.customer_detail.as_view()),
]

coffee_app/models.py
from django import contrib
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=100, null=True)
    email = models.CharField(max_length=100, null=True)
    def __str__(self):
        return self.name


class Item( models.Model):#akak product
    """items"""
    name = models.CharField(max_length=100)
    price = models.IntegerField()
    id = models.AutoField(primary_key=True)
    image = models.ImageField(null=True)
    description  = models.CharField(max_length=200, default="this is the best drink")

    TYPE_STATUS = (
        ('favourite', 'favourite'),
        ('coffee', 'coffee'),
        ('fruit tea', 'fruit tea'),
        ('ICE BLENDED', 'ice blended'),
        ('snack', 'snack'),
    )
    type = models.CharField(max_length=11,choices=TYPE_STATUS,blank=True,default='favourite',
                            help_text= "Input type for item")
    def __str__(self):
        return self.name

###promotion
class Promotions(models.Model):
    id = models.AutoField(primary_key=True)
    avatar = models.ImageField(null=False)
    content = models.CharField(max_length=80, default ="Discount 90%")
    expired = models.CharField(max_length=30, default="het han trong 2 ngay")
    discount = models.FloatField(default=0.1)

class Order(models.Model):
    date_ordered = models.DateTimeField(auto_now_add=True)
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True)
    transaction_ID = models.CharField(max_length=100, null=True)
    complete = models.BooleanField(default=False, null=True)
    promotion = models.ForeignKey(Promotions,null=True,blank=True,on_delete=models.SET_NULL)

    def __str__(self):
        return str(self.id)
    @property
    def get_cart_total_before_promotion(self):
        orderitems = self.orderitem_set.all()
        total=0
        for item in orderitems:
            total += item.get_total
        ###check promotion
        return total
    @property
    def get_cart_total(self):
        orderitems = self.orderitem_set.all()
        total=0
        promo = self.promotion
        for item in orderitems:
            total += item.get_total
        ###check promotion
        if promo is None:
            print("null")
        else:
            total *= (1-promo.discount)
        return total
    @property
    def get_cart_quantiy(self):
        orderitems = self.selforderitem_set.all()
        total = sum([item.quantity for item in orderitems])
        return total


class OrderItem(models.Model):
    date_add = models.DateTimeField(auto_now_add=True)
    item = models.ForeignKey(Item, on_delete=models.SET_NULL, null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True)
    quantity = models.IntegerField(default=0, null=True)
    size = models.CharField(max_length=1,default="S")
    note = models.CharField(max_length=50, default="normal")
    @property
    def get_total(self):
        plus = 0
        if self.size == 'M':
            plus = 5000
        elif self.size == 'L':
            plus = 10000
        total = self.item.price * self.quantity + plus*self.quantity
        return total
    @property
    def get_final_price(self):
        plus = 0
        if self.size == 'M':
            plus = 5000
        elif self.size == 'L':
            plus = 10000
        total = self.item.price + plus
        return total

class ShippingAddress(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True)
    city = models.CharField(max_length=100, null=True)
    zipcode = models.CharField(max_length=100, null=True)
    address = models.CharField(max_length=100, null=True)
    fname = models.CharField(max_length=100, null=True)
    phone = models.CharField(max_length=100, null=True)
    date_add = models.DateTimeField(auto_now_add=True)
    instructions = models.CharField(max_length=100, null=True)

    def __str__(self):
        return self.address


###news 

class News(models.Model):
    title = models.CharField(max_length=100, null=False, default="title here")
    avatar = models.ImageField(null=False)
    content = models.CharField(max_length=300, default="pls input here")

    def __str__(self):
        return self.title

coffee_app/views.py
from django.shortcuts import render
from .models import Customer, Item, News, Order, OrderItem, Promotions, ShippingAddress
from django.core import serializers
from django.http import HttpResponse
from .serializer import ItemSerializers
from django.http.response import JsonResponse
import json
import datetime

import json
# Create your views here.
def index(request):
    """The home page """
    return render(request, 'coffee_app/index.html')

def order(request):
    """The cart page"""
    if request.user.is_authenticated:
        customer = request.user.customer
        order, created = Order.objects.get_or_create(customer=customer, complete=False)
        items = order.orderitem_set.all()
    else:
        items = []
        order = {'get_cart_total':0, 'get_cart_quantity':0,'get_cart_total_before_promotion':0}
    if order.promotion is None:
        context = {'items': items, 'order':order}
        #print("abc")
    else:
        context = {'items': items, 'order':order, 'promotion':order.promotion.content}
    return render(request, 'coffee_app/order.html', context)

def news(request):
    """The home page """
    return render(request, 'coffee_app/news.html')

def news_detail(request,id):
    """The home page """
    news = News.objects.get(id=id)
    context = {'news':news}
    return render(request, 'coffee_app/newsdetail.html',context)

def orderhistory(request):
    """The home page """
    orders = Order.objects.filter(customer=request.user.customer).order_by('date_ordered')
    context = {'orders':orders}
    return render(request, 'coffee_app/orderhistory.html',context)
    
def updateItem(request):
    data = json.loads(request.body)
    itemId = data['itemId']
    action = data['action']
    quantity = data['quantity']
    size = data['size']
    note = data['note']
    print(itemId)
    print(action)

    customer = request.user.customer
    item = Item.objects.get(id = itemId)

    order, created = Order.objects.get_or_create(customer=customer, complete=False)
    orderItem, created = OrderItem.objects.get_or_create(order=order, item=item, quantity = quantity, size = size, note = note)

    #if action == 'add':
    #   orderItem.quantity += 1
    #elif action == 'remove':
    #    orderItem.quantity -= 1

    orderItem.save()

    #if orderItem.quantity <= 0:
    #    orderItem.delete()

    return JsonResponse('item was added',safe=False)

def processOrder(request):
    print('Data: ',request.body)
    transaction_id = datetime.datetime.now().timestamp()
    data = json.loads(request.body)
    if request.user.is_authenticated:
        customer = request.user.customer
        order, created = Order.objects.get_or_create(customer=customer, complete=False)
        total = float(data['form']['total'])
        order.transaction_ID = transaction_id
    else:
        print("not logged in")
    print(total)
    if total == order.get_cart_total:
        order.complete = True
    order.save()
    ShippingAddress.objects.create(
    customer = customer,
    order = order,
    address = data['shipping']['address'],
    phone = data['shipping']['phone'],
    fname = data['shipping']['fname'],
    instructions = data['shipping']['instructions'],
    date_add = data['shipping']['bday']
    )
    return JsonResponse('payment complete',safe=False)
####remove item
def removeItem(request):
    data = json.loads(request.body)
    itemId = data['itemIdtoremove']
    orderItem, created = OrderItem.objects.get_or_create(id = itemId)
    orderItem.delete()
    return JsonResponse('remove successfully',safe=False)

###promotion
def update_promotion(request):
    data = json.loads(request.body)
    proId = data['promotionId']
    print(proId)
    if request.user.is_authenticated:
        promotion = Promotions.objects.get(id = proId)
        customer = request.user.customer
        thisorder, created = Order.objects.get_or_create(customer=customer, complete=False)
        thisorder.promotion = promotion
        
        thisorder.get_cart_total_before_promotion
        thisorder.get_cart_total
        thisorder.save()
    else:
        print("not logging")
    
    return JsonResponse('promotion was added',safe=False)

# def items(request):
#     items = Item.objects.order_by('price')
#     context = {'items': items}
#     return render(request, 'coffee_app/index.html', context)
def items(request):
    items = Item.objects.all().values()

    items_list = list(items)

    data = json.dumps(items_list)
    return HttpResponse(data, content_type="application/json")
####item detail
def items_detail_1(request):
    items = Item.objects.raw('SELECT * FROM coffee_app_Item WHERE type="favourite"')

    serializer = ItemSerializers(items, many = True)

    return JsonResponse(serializer.data, safe = False)

def items_detail_2(request):
    items = Item.objects.raw('SELECT * FROM coffee_app_Item WHERE type="coffee"')

    serializer = ItemSerializers(items, many = True)

    return JsonResponse(serializer.data, safe = False)

def items_detail_3(request):
    items = Item.objects.raw('SELECT * FROM coffee_app_Item WHERE type="fruit tea"')

    serializer = ItemSerializers(items, many = True)

    return JsonResponse(serializer.data, safe = False)

def items_detail_4(request):
    items = Item.objects.raw('SELECT * FROM coffee_app_Item WHERE type="ICE BLENDED"')

    serializer = ItemSerializers(items, many = True)

    return JsonResponse(serializer.data, safe = False)

def items_detail_5(request):
    items = Item.objects.raw('SELECT * FROM coffee_app_Item WHERE type="snack"')

    serializer = ItemSerializers(items, many = True)

    return JsonResponse(serializer.data, safe = False)


###news

def get_news(request):
    items = News.objects.all().values()

    items_list = list(items)

    data = json.dumps(items_list)
    return HttpResponse(data, content_type="application/json")

###Promotion

def get_promotion(request):
    items = Promotions.objects.all().values()

    items_list = list(items)

    data = json.dumps(items_list)
    return HttpResponse(data, content_type="application/json")

def store(request):
    """The home page """
    return render(request, 'coffee_app/store.html')

coffee_app/templates/coffee_app/items.html
{% block content %}
  <p>itmes</p>
  <ul>
    {% for item in items %}
      <li>{{ item }}</li>
    {% empty %}
      <li>No items have been added yet.</li>
    {% endfor %}
  </ul>
{% endblock content %}

coffee_app/templates/coffee_app/orderhistory.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tea-Rex Cafe</title>
    <link rel="icon" href="{% static './assets/images/Logo.jpg' %}" type="image/x-icon" />
    <link rel="stylesheet" href="{% static './assets/css/base.css' %} ">
    <link rel="stylesheet" href="{% static './assets/css/main.css' %} ">
    <link rel="stylesheet" href=" {% static './components2/orderhistory/style.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <link  href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.6.0/mdb.min.css"  rel="stylesheet"/>
    <link rel="stylesheet" href=" {% static './assets/fonts/fontawesome-free-6.0.0-beta2-web/css/all.css' %} ">
    <link  href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"  rel="stylesheet"/>
</head>
<body>
  {% block content %}



    <div class="app">
        <header class="header">
            <div class="container">
                <nav class="header__nav">
                    <div class="header__info">
                        <a href="{% url 'coffee_app:index' %}"class ="header__nav-logo--link">
                            <img src="{% static './assets/images/Logo.jpg' %}" alt="logo" class ="header__nav-logo" >
                        </a>
                          
                        <!-- <div class="header__nav-delibery">
                            <img src="./assets/images/Delivery2.png" alt="delibery" class = "header__delibery--logo">
                            <ul class="header__nav-delibery-list">
                                <div class="delibery__address">
                                    <li class="header__nav-delibery-item delibery__address-head">DELIBERY</li>
                                    <li class="header__nav-delibery-item">Filling the address</li>
                                </div>
                            </ul>
                        </div> -->

                        <ul class="header__nav-list ">
                            <li class="header__nav-item">
                                <a href="{% url 'coffee_app:index' %}" class="header__nav-item--link">HOME</a>
                            </li>
     
                            <li class="header__nav-item">
                                <a href="{% url 'coffee_app:order' %}" class="header__nav-item--link">ORDER</a>
                            </li>
     
                            <li class="header__nav-item"> 
                                <a href="{% url 'coffee_app:news' %}" class="header__nav-item--link">NEWS</a>
                            </li>       
     
                             <li class="header__nav-item">
                                <a href="javascript:void(0)" class="header__nav-item--link promotelink" onclick="showPromotion()">PROMOTION</a>
                             </li>
                        </ul>
                        <label for="nav-mobile-input" class="nav__bars-btn">
                          <i class="nav__bars-btn--icon fas fa-bars"></i>
                      </label>
  
                      <input type="checkbox" hidden name="" id="nav-mobile-input" class="nav-input">
  
                      <label for="nav-mobile-input" class="nav__overlay"> </label>
                      <div class="nav__mobile">
                          <label for="nav-mobile-input" class="nav__mobile-close">
                              <i class="nav__mobile-close--icon fas fa-times"></i>
                          </label>
                          <ul class="nav__mobile-list ">
                              <li class="nav__mobile-item">
                                  <a href=" {% url 'coffee_app:index' %}" class="nav__mobile-item--link">
                                      <i class="nav__mobile-icon fas fa-home"></i>
                                      HOME
                                  </a>
                              </li>
          
                              
  
                              <li class="nav__mobile-item"> 
                                  <a href="{% url 'coffee_app:news' %} " class="nav__mobile-item--link">
                                      <i class="nav__mobile-icon fas fa-newspaper"></i>
                                      NEWS
                                  </a>
                              </li>  
                          
                              <li class="nav__mobile-item"> 
                                  <a href="javascript:void(0)" class="nav__mobile-item--link promotelink" onclick="showPromotion()">
                                      <i class="nav__mobile-icon fas fa-ad"></i>
                                      PROMOTION
                                  </a>
                              </li>  
                              
                              <li class="nav__mobile-item"> 
                                  <a href="{% url 'users:login' %}" class="nav__mobile-item--link">
                                      <i class="nav__mobile-icon fas fa-user"></i>
                                      LOGIN
                                  </a>
                              </li>  
                              
                              <li class="nav__mobile-item"> 
                                  <a href="{% url 'coffee_app:order' %}" class="nav__mobile-item--link">
                                      <i class="nav__mobile-icon fas fa-cart-plus"></i>
                                      ORDER CONFIRMATION
                                  </a>
                              </li>  
                          </ul>
                      </div>
                    </div>
                    
                    <ul class="header__nav-list">
                            <li class="header__nav-user"> 
                            
                                <img src="{% static './assets/images/Login.70dc3d8.png' %}" alt="login" onclick="clickLogin()" class="header__nav-login" >
                                <div class="popup-login">
                                    <img data-v-1c02541c="" onClick="closeClickLogin()" src="data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTYiIGhlaWdodD0iMTYiIHZpZXdCb3g9IjAgMCAxNiAxNiIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHBhdGggZD0iTTAgMTUuMzg0NkwxNS4zODQ2IDBMMTYgMC42MTUzODRMMC42MTUzODQgMTZMMCAxNS4zODQ2WiIgZmlsbD0iYmxhY2siLz4KPHBhdGggZD0iTTYuNjM5NzVlLTA2IDAuNjE1Mzk1TDE1LjM4NDYgMTZMMTYgMTUuMzg0NkwwLjYxNTM5MSAxLjAzNzQ2ZS0wNUw2LjYzOTc1ZS0wNiAwLjYxNTM5NVoiIGZpbGw9ImJsYWNrIi8+Cjwvc3ZnPgo=" class="icon-close-card">
                                    <ul>
                                      <li class="fas fa-history"> Order history</li>
                                      
                                      {%if user.is_authenticated %}
                                      <li class="fas fa-sign-in-alt">   Hello, {{user.username}} </li>
                                      <a href="{% url 'users:logout' %}"><li class="fas fa-sign-in-alt"> Logout</li></a> 
                                      {%else%}
                                      <a href="{% url 'users:login' %}"><li class="fas fa-sign-in-alt"> Login</li></a> 
                                      {%endif%}
                                      <!-- ===================== -->
                                  </ul>
                                </div>
                            </li>       
     
                             <li class="header__nav-user"  class="header__nav-cart">     
                                 <a href="{% url 'coffee_app:order' %}">
                                    <img data-v-1c02541c="" src="{% static './assets/images/Carticon.373916c.png' %}" alt="cart" class="header__nav-cart" > 
                                 </a>     
                                                 
                             </li>
                    </ul>
                </nav>
            </div>
        </header>
    </div>  
    <div class="ordershistory-container ">
        <div class="container">
    <span id="horder">My order history</span>
    
    {% for order in orders %}    
    <div class="orderhistory">
        <div class="dateOrder">
          {{order.date_ordered}} 
        </div>
        <table class="table table-hover">
            <thead>
              <tr>
                <th scope="col">Product</th>
                <th scope="col">Size</th>
                <th scope="col">Quantity</th>
                <th scope="col">Price</th>
                <th scope="col">Total</th>
              </tr>
            </thead>
            <tbody>
              {% for item in order.orderitem_set.all %}
              <tr>
                <th class="col-5">
                    <div class="orderhistory-product">
                    <img src="/static/assets/images/{{item.item.image}}" alt="">
                    <div class="hoder-detail">
                        <span>{{item.item.name}}</span>
                        <span>{{item.item.size}}</span>
                        <span class="hoder-note">Note: {{item.note}}</span>
                    </div>
                </div>
                </th>
                <td>{{item.size}}</td>
                <td>{{item.quantity}}</td>
                <td>{{item.item.price}}</td>
                <td>{{item.get_total}}</td>
              </tr>


              {%endfor%}
            </tbody>
          </table>
          <div class="hoder-sumary">


            {% for address in order.shippingaddress_set.all %}
              <div class="hoder-shipping">
                <span>Name: {{address.fname}}</span>
                <span>Note: {{address.instructions}}</span>
                <span>Address: {{address.address}}</span>
              </div>
            {%endfor%}


              <div class="hoder-sumary--price">
                <span>Total Summary</span>
                <div class="sub-summary">
                    <span>Price: {{order.get_cart_total_before_promotion}} VND</span>
                    <span>voucher: {{order.promotion.content}}</span>                    
                </div>
                <span>Total: {{order.get_cart_total}}VND</span>
              </div>
          </div>
          <div style="clear:both;"></div>
    </div>
    {% endfor %}

    {% endblock content %}

    </div>
        
       
    
    <script src=" {% static './components2/orderhistory/style.css' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.6.0/mdb.min.js"></script>
</body>
</html>

coffee_app/templates/coffee_app/temp.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link
  href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.6.0/mdb.min.css"
  rel="stylesheet"
/>
    <title>Document</title>
</head>
<body>
<div class="container">
    <!-- Carousel wrapper -->
<div
id="carouselBasicExample"
class="carousel slide carousel-fade"
data-mdb-ride="carousel"
>
<!-- Indicators -->
<div class="carousel-indicators">
  <button
    type="button"
    data-mdb-target="#carouselBasicExample"
    data-mdb-slide-to="0"
    class="active"
    aria-current="true"
    aria-label="Slide 1"
  ></button>
  <button
    type="button"
    data-mdb-target="#carouselBasicExample"
    data-mdb-slide-to="1"
    aria-label="Slide 2"
  ></button>
  <button
    type="button"
    data-mdb-target="#carouselBasicExample"
    data-mdb-slide-to="2"
    aria-label="Slide 3"
  ></button>
</div>

<!-- Inner -->
<div class="carousel-inner">
  <!-- Single item -->
  <div class="carousel-item active">
    <img
      src="https://mdbootstrap.com/img/Photos/Slides/img%20(15).jpg"
      class="d-block w-100"
      alt="..."
    />
    <div class="carousel-caption d-none d-md-block">
      <h5>First slide label</h5>
      <p>
        Nulla vitae elit libero, a pharetra augue mollis interdum.
      </p>
    </div>
  </div>

  <!-- Single item -->
  <div class="carousel-item">
    <img
      src="https://mdbootstrap.com/img/Photos/Slides/img%20(22).jpg"
      class="d-block w-100"
      alt="..."
    />
    <div class="carousel-caption d-none d-md-block">
      <h5>Second slide label</h5>
      <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit.
      </p>
    </div>
  </div>

  <!-- Single item -->
  <div class="carousel-item">
    <img
      src="https://mdbootstrap.com/img/Photos/Slides/img%20(23).jpg"
      class="d-block w-100"
      
      alt="..."
    />
    <div class="carousel-caption d-none d-md-block">
      <h5>Third slide label</h5>
      <p>
        Praesent commodo cursus magna, vel scelerisque nisl consectetur.
      </p>
    </div>
  </div>
</div>
<!-- Inner -->

<!-- Controls -->
<button
  class="carousel-control-prev"
  type="button"
  data-mdb-target="#carouselBasicExample"
  data-mdb-slide="prev"
>
  <span class="carousel-control-prev-icon" aria-hidden="true"></span>
  <span class="visually-hidden">Previous</span>
</button>
<button
  class="carousel-control-next"
  type="button"
  data-mdb-target="#carouselBasicExample"
  data-mdb-slide="next"
>
  <span class="carousel-control-next-icon" aria-hidden="true"></span>
  <span class="visually-hidden">Next</span>
</button>
</div>
<!-- Carousel wrapper -->
</div>

<!-- <iframe width="560" height="315" src="https://mdbootstrap.com/api/snippets/embed/3426502/fullscreen" frameborder="0"></iframe> -->


<script
  type="text/javascript"
  src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.6.0/mdb.min.js"
></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
</body>
</html>l